/**
 * Country Code Mapping for CEAC DS-160 Form
 * 
 * Maps our form country names to CEAC's 3-4 letter country codes
 */

export const countryCodeMapping: Record<string, string> = {
  // Major countries - Updated to match CEAC website format
  'UNITED STATES OF AMERICA': 'USA',
  'CANADA': 'CAN',
  'UNITED KINGDOM': 'GRBR',
  'AUSTRALIA': 'ASTL',
  'INDIA': 'IND',
  'CHINA': 'CHIN',
  'JAPAN': 'JPN',
  'GERMANY': 'GER',
  'FRANCE': 'FRAN',
  'BRAZIL': 'BRZL',
  'MEXICO': 'MEX',
  'NIGERIA': 'NRA',
  'KENYA': 'KENY',
  'SOUTH AFRICA': 'SAFR',
  'ITALY': 'ITLY',
  'SPAIN': 'SPN',
  'RUSSIA': 'RUS',
  'NETHERLANDS': 'NETH',
  'SWEDEN': 'SWDN',
  'NORWAY': 'NORW',
  'DENMARK': 'DEN',
  'FINLAND': 'FIN',
  'POLAND': 'POL',
  'PORTUGAL': 'PORT',
  'IRELAND': 'IRE',
  'NEW ZEALAND': 'NZLD',
  'PAKISTAN': 'PKST',
  'BANGLADESH': 'BANG',
  'SRI LANKA': 'SRL',
  'NEPAL': 'NEP',
  'PHILIPPINES': 'PHIL',
  'INDONESIA': 'IDSA',
  'MALAYSIA': 'MLAS',
  'SINGAPORE': 'SING',
  'THAILAND': 'THAI',
  'VIETNAM': 'VTNM',
  'TURKEY': 'TRKY',
  'SAUDI ARABIA': 'SARB',
  'UNITED ARAB EMIRATES': 'UAE',
  'QATAR': 'QTAR',
  'EGYPT': 'EGYP',
  'ISRAEL': 'ISRL',
  'ARGENTINA': 'ARG',
  'CHILE': 'CHIL',
  'COLOMBIA': 'COL',
  'PERU': 'PERU',
  
  // Additional countries from CEAC dropdown - Updated to match CEAC website format
  'AFGHANISTAN': 'AFGH',
  'ALBANIA': 'ALB',
  'ALGERIA': 'ALGR',
  'ANDORRA': 'ANDO',
  'ANGOLA': 'ANGL',
  'ANGUILLA': 'ANGU',
  'ANTIGUA AND BARBUDA': 'ANTI',
  'ARMENIA': 'ARM',
  'AUSTRIA': 'AUST',
  'AZERBAIJAN': 'AZR',
  'BAHAMAS': 'BAMA',
  'BAHRAIN': 'BAHR',
  'BARBADOS': 'BRDO',
  'BELARUS': 'BYS',
  'BELGIUM': 'BELG',
  'BELIZE': 'BLZ',
  'BENIN': 'BENN',
  'BERMUDA': 'BERM',
  'BHUTAN': 'BHU',
  'BOLIVIA': 'BOL',
  'BOSNIA-HERZEGOVINA': 'BIH',
  'BOTSWANA': 'BOT',
  'BRUNEI': 'BRNI',
  'BULGARIA': 'BULG',
  'BURKINA FASO': 'BURK',
  'BURMA': 'BURM',
  'BURUNDI': 'BRND',
  'CAMBODIA': 'CBDA',
  'CAMEROON': 'CMRN',
  'CABO VERDE': 'CAVI',
  'CAYMAN ISLANDS': 'CAYI',
  'CENTRAL AFRICAN REPUBLIC': 'CAFR',
  'CHAD': 'CHAD',
  'COMOROS': 'COMO',
  'CONGO, DEMOCRATIC REPUBLIC OF THE': 'COD',
  'CONGO, REPUBLIC OF THE': 'CONB',
  'COSTA RICA': 'CSTR',
  'COTE D`IVOIRE': 'IVCO',
  'CROATIA': 'HRV',
  'CUBA': 'CUBA',
  'CYPRUS': 'CYPR',
  'CZECH REPUBLIC': 'CZEC',
  'DJIBOUTI': 'DJI',
  'DOMINICA': 'DOMN',
  'DOMINICAN REPUBLIC': 'DOMR',
  'ECUADOR': 'ECUA',
  'EL SALVADOR': 'ELSL',
  'EQUATORIAL GUINEA': 'EGN',
  'ERITREA': 'ERI',
  'ESTONIA': 'EST',
  'ESWATINI': 'SZLD',
  'ETHIOPIA': 'ETH',
  'FIJI': 'FIJI',
  'GABON': 'GABN',
  'GAMBIA, THE': 'GAM',
  'GEORGIA': 'GEO',
  'GHANA': 'GHAN',
  'GIBRALTAR': 'GIB',
  'GREECE': 'GRC',
  'GRENADA': 'GREN',
  'GUATEMALA': 'GUAT',
  'GUINEA': 'GNEA',
  'GUINEA - BISSAU': 'GUIB',
  'GUYANA': 'GUY',
  'HAITI': 'HAT',
  'HOLY SEE (VATICAN CITY)': 'VAT',
  'HONDURAS': 'HOND',
  'HONG KONG BNO': 'HOKO',
  'HONG KONG SAR': 'HNK',
  'HUNGARY': 'HUNG',
  'ICELAND': 'ICLD',
  'IRAN': 'IRAN',
  'IRAQ': 'IRAQ',
  'JAMAICA': 'JAM',
  'JORDAN': 'JORD',
  'KAZAKHSTAN': 'KAZ',
  'KIRIBATI': 'KIRI',
  'KOREA, DEMOCRATIC REPUBLIC OF (NORTH)': 'PRK',
  'KOREA, REPUBLIC OF (SOUTH)': 'KOR',
  'KOSOVO': 'KSV',
  'KUWAIT': 'KUWT',
  'KYRGYZSTAN': 'KGZ',
  'LAOS': 'LAOS',
  'LATVIA': 'LATV',
  'LEBANON': 'LEBN',
  'LESOTHO': 'LES',
  'LIBERIA': 'LIBR',
  'LIBYA': 'LBYA',
  'LIECHTENSTEIN': 'LCHT',
  'LITHUANIA': 'LITH',
  'LUXEMBOURG': 'LXM',
  'MACAU': 'MAC',
  'MACEDONIA, NORTH': 'MKD',
  'MADAGASCAR': 'MADG',
  'MALAWI': 'MALW',
  'MALDIVES': 'MLDV',
  'MALI': 'MALI',
  'MALTA': 'MLTA',
  'MARSHALL ISLANDS': 'RMI',
  'MAURITANIA': 'MAUR',
  'MAURITIUS': 'MRTS',
  'MICRONESIA': 'FSM',
  'MOLDOVA': 'MLD',
  'MONACO': 'MON',
  'MONGOLIA': 'MONG',
  'MONTENEGRO': 'MTG',
  'MONTSERRAT': 'MONT',
  'MOROCCO': 'MORO',
  'MOZAMBIQUE': 'MOZ',
  'NAMIBIA': 'NAMB',
  'NAURU': 'NAU',
  'NICARAGUA': 'NIC',
  'NIGER': 'NIR',
  'OMAN': 'OMAN',
  'PALAU': 'PALA',
  'PALESTINIAN AUTHORITY': 'PAL',
  'PANAMA': 'PAN',
  'PAPUA NEW GUINEA': 'PNG',
  'PARAGUAY': 'PARA',
  'PITCAIRN ISLANDS': 'PITC',
  'ROMANIA': 'ROM',
  'RWANDA': 'RWND',
  'SAMOA': 'WSAM',
  'SAN MARINO': 'SMAR',
  'SAO TOME AND PRINCIPE': 'STPR',
  'SENEGAL': 'SENG',
  'SERBIA': 'SBA',
  'SEYCHELLES': 'SEYC',
  'SIERRA LEONE': 'SLEO',
  'SLOVAKIA': 'SVK',
  'SLOVENIA': 'SVN',
  'SOLOMON ISLANDS': 'SLMN',
  'SOMALIA': 'SOMA',
  'SOUTH SUDAN': 'SSDN',
  'ST. HELENA': 'SHEL',
  'ST. KITTS AND NEVIS': 'STCN',
  'ST. LUCIA': 'SLCA',
  'ST. VINCENT AND THE GRENADINES': 'STVN',
  'SUDAN': 'SUDA',
  'SURINAME': 'SURM',
  'SWITZERLAND': 'SWTZ',
  'SYRIA': 'SYR',
  'TAIWAN': 'TWAN',
  'TAJIKISTAN': 'TJK',
  'TANZANIA': 'TAZN',
  'TIMOR-LESTE': 'TMOR',
  'TOGO': 'TOGO',
  'TONGA': 'TONG',
  'TRINIDAD AND TOBAGO': 'TRIN',
  'TUNISIA': 'TNSA',
  'TURKMENISTAN': 'TKM',
  'TURKS AND CAICOS ISLANDS': 'TCIS',
  'TUVALU': 'TUV',
  'UGANDA': 'UGAN',
  'UKRAINE': 'UKR',
  'URUGUAY': 'URU',
  'UZBEKISTAN': 'UZB',
  'VANUATU': 'VANU',
  'VENEZUELA': 'VENZ',
  'VIRGIN ISLANDS, BRITISH': 'BRVI',
  'WALLIS AND FUTUNA ISLANDS': 'WAFT',
  'WESTERN SAHARA': 'SSAH',
  'YEMEN': 'YEM',
  'ZAMBIA': 'ZAMB',
  'ZIMBABWE': 'ZIMB'
}

/**
 * Get CEAC country code from country name
 */
export function getCountryCode(countryName: string): string | null {
  return countryCodeMapping[countryName] || null
}

/**
 * Get country name from CEAC country code
 */
export function getCountryName(countryCode: string): string | null {
  for (const [name, code] of Object.entries(countryCodeMapping)) {
    if (code === countryCode) {
      return name
    }
  }
  return null
}
