[phases.setup]
nixPkgs = [
  'nodejs_18',
  'glib',
  'nss',
  'nspr',
  'atk',
  'at-spi2-atk',
  'cups',
  'gtk3',
  'xorg.libXcomposite',
  'xorg.libXdamage',
  'xorg.libXrandr',
  'mesa',
  'expat',
  'xorg.libXfixes',
  'xorg.libXScrnSaver',
  'alsa-lib'
]

[phases.install]
cmds = [
  'npm ci',
  'npx playwright install --with-deps chromium'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm run worker:prod'
