[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run worker:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
variables = { NODE_ENV = "production" }

[services.worker]
source = "."
