[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run worker:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
variables = { 
  NODE_ENV = "production", 
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "0",
  PLAYWRIGHT_BROWSERS_PATH = "/root/.cache/ms-playwright"
}

[services.worker]
source = "."
